/* Familiens Kostkompas V4.6 – sikker synkronisering */
(() => {
  'use strict';
  const CLIENT_ID_KEY='kostkompas-client-id-v46';
  let syncBusy=false;
  function clientId(){let x=localStorage.getItem(CLIENT_ID_KEY);if(!x){x='client-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10);localStorage.setItem(CLIENT_ID_KEY,x)}return x}
  function parsePlan(x){if(!x)return null;try{const p=typeof x==='string'?JSON.parse(x):x;return p&&Array.isArray(p.items)&&p.items.length?p:null}catch(e){return null}}
  function ms(x){const n=Date.parse(x||'');return Number.isFinite(n)?n:0}
  function savedMs(p){return ms(p?._sync?.savedAt)}
  function createdMs(p){const n=Number(p?.created||0);return Number.isFinite(n)?n:0}
  function attach(p){if(!p)return p;p.recipeFeedback=recipeFeedback;p.pantryState=pantryState;p.shoppingChecks=shoppingChecks;p.customRecipes=customRecipes;p.planHistory=planHistory;return p}
  function mark(p){if(!p)return;const now=new Date().toISOString();p._sync={...(p._sync||{}),savedAt:now,clientId:clientId(),dirty:true};localStorage.setItem('kostkompas-current-plan',JSON.stringify(p))}
  async function snapshot(){const h=await cloudHeaders();if(!h)throw new Error('Ikke logget ind');const r=await fetch(`${SUPABASE_URL}/rest/v1/active_plan?id=eq.1&select=plan_data,updated_at`,{headers:h,cache:'no-store'});if(!r.ok)throw new Error('Kunne ikke hente fælles madplan');const rows=await r.json();return rows[0]||{plan_data:{},updated_at:null}}
  window.fetchCloudPlan=async()=>{const s=await snapshot();return s.plan_data||{}};
  window.saveCloudState=async state=>{const h=await cloudHeaders();if(!h)throw new Error('Ikke logget ind');const r=await fetch(`${SUPABASE_URL}/rest/v1/active_plan?id=eq.1`,{method:'PATCH',headers:{...h,'Prefer':'return=representation'},body:JSON.stringify({plan_data:state||{},updated_at:new Date().toISOString()})});if(!r.ok)throw new Error('Cloud-save mislykkedes: '+await r.text());const rows=await r.json();return rows[0]||null};
  window.saveCloudPlan=async function(plan=currentPlan){if(!plan)return null;attach(plan);if(!plan._sync?.savedAt)mark(plan);else{plan._sync.clientId=clientId();plan._sync.dirty=true;localStorage.setItem('kostkompas-current-plan',JSON.stringify(plan))}const row=await saveCloudState(plan);plan._sync={...(plan._sync||{}),dirty:false,serverUpdatedAt:row?.updated_at||new Date().toISOString()};localStorage.setItem('kostkompas-current-plan',JSON.stringify(plan));return row};
  window.persistPlan=function(){if(!currentPlan)return Promise.resolve();attach(currentPlan);mark(currentPlan);return saveCloudPlan(currentPlan).catch(err=>{console.error(err);currentPlan._sync={...(currentPlan._sync||{}),dirty:true};localStorage.setItem('kostkompas-current-plan',JSON.stringify(currentPlan));return Promise.reject(err)})};
  function newest(local,remote){const l=savedMs(local),r=savedMs(remote);if(l&&r)return l>r?'local':'remote';if(l&&!r)return'local';if(!l&&r)return'remote';const lc=createdMs(local),rc=createdMs(remote);if(lc&&rc&&lc>rc)return'local';return remote?'remote':local?'local':'none'}
  function mergeHouse(remote){if(!remote||typeof remote!=='object')return;if(remote.recipeFeedback&&typeof remote.recipeFeedback==='object')recipeFeedback=remote.recipeFeedback;if(remote.pantryState&&typeof remote.pantryState==='object')pantryState=remote.pantryState;if(remote.shoppingChecks&&typeof remote.shoppingChecks==='object')shoppingChecks=remote.shoppingChecks;if(Array.isArray(remote.customRecipes))customRecipes=remote.customRecipes;if(Array.isArray(remote.planHistory))planHistory=remote.planHistory;if(typeof rebuildRecipes==='function')rebuildRecipes();if(typeof saveHouseholdStateLocal==='function')saveHouseholdStateLocal();if(typeof persistRecipeFeedbackLocal==='function')persistRecipeFeedbackLocal()}
  window.syncAfterLogin=async function(){loadRecipeFeedback();loadHouseholdState();const preserved=parsePlan(window.__kostkompasPreAppPlan),stored=parsePlan(localStorage.getItem('kostkompas-current-plan'));let local=stored;if(preserved&&(!local||newest(preserved,local)==='local'))local=preserved;const s=await snapshot(),remote=parsePlan(s.plan_data);mergeHouse(s.plan_data||{});const choice=newest(local,remote);if(choice==='local'){currentPlan=local;attach(currentPlan);localStorage.setItem('kostkompas-current-plan',JSON.stringify(currentPlan));await saveCloudPlan(currentPlan)}else if(choice==='remote'){currentPlan=remote;attach(currentPlan);currentPlan._sync={...(currentPlan._sync||{}),dirty:false,serverUpdatedAt:s.updated_at||null};localStorage.setItem('kostkompas-current-plan',JSON.stringify(currentPlan))}else currentPlan=null;window.__kostkompasPreAppPlan=null};
  window.activateDraftPlan=async function(){if(!draftPlan)return;if(currentPlan?.items?.length&&typeof archiveCurrentPlan==='function')archiveCurrentPlan();currentPlan=draftPlan;draftPlan=null;shoppingChecks={};attach(currentPlan);mark(currentPlan);try{[...document.querySelectorAll('button')].filter(b=>/Brug denne madplan/i.test(b.textContent||'')).forEach(b=>{b.disabled=true;b.textContent='☁ Gemmer og synkroniserer…'});await saveCloudPlan(currentPlan);if(typeof saveHouseholdStateLocal==='function')saveHouseholdStateLocal();renderCurrentPlan()}catch(err){console.error(err);renderCurrentPlan();setTimeout(()=>alert('Madplanen er gemt på denne enhed, men kunne ikke synkroniseres endnu. Appen prøver igen, når du vender tilbage.'),50)}};
  async function syncLatest(){if(syncBusy||!cloudSession?.access_token)return;syncBusy=true;try{const s=await snapshot(),remote=parsePlan(s.plan_data),local=parsePlan(localStorage.getItem('kostkompas-current-plan'))||currentPlan;if(!remote&&local){if(local?._sync?.dirty)await saveCloudPlan(local);return}if(!remote)return;const choice=newest(local,remote);if(choice==='local'&&local?._sync?.dirty){currentPlan=local;await saveCloudPlan(currentPlan)}else if(choice==='remote'){mergeHouse(s.plan_data||{});currentPlan=remote;attach(currentPlan);currentPlan._sync={...(currentPlan._sync||{}),dirty:false,serverUpdatedAt:s.updated_at||null};localStorage.setItem('kostkompas-current-plan',JSON.stringify(currentPlan))}}catch(e){console.warn('Baggrundssynkronisering fejlede',e)}finally{syncBusy=false}}
  setTimeout(async()=>{try{if(await refreshCloudSession())await syncAfterLogin()}catch(e){console.warn('V4.6 initial sync failed',e)}},350);
  window.addEventListener('focus',syncLatest);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')syncLatest()});setInterval(syncLatest,30000);
})();